/*
 Polyfill.js - v0.1.0

 Copyright (c) 2015 Philip Walton <http://philipwalton.com>
 Released under the MIT license

 Date: 2015-06-21
*/
!function(l,n,B){function v(a){return a.replace(/^\s+|\s+$/g,"")}function C(a,c){var b,f=0;if(!a||!c)return!1;for(;b=c[f++];)if(a===b)return!0;return!1}function m(a){var c,b=0;for(this._rules=[];c=a[b++];)this._rules.push(new w(c))}function w(a){this._rule=a}function h(a){return this instanceof h?(this._options=a,a.keywords||(this._options={keywords:a}),this._promise=[],this._getStylesheets(),this._downloadStylesheets(),this._parseStylesheets(),this._filterCSSByKeywords(),this._buildMediaQueryMap(),
this._reportInitialMatches(),void this._addMediaListeners()):new h(a)}B=RegExp("^"+String({}.valueOf).replace(/[.*+?\^${}()|\[\]\\]/g,"\\$&").replace(/valueOf|for [^\]]+/g,".+?")+"$");var D=function(){var a=n.getElementsByTagName("base")[0],c=/^([a-zA-Z:]*\/\/)/;return function(b){return!c.test(b)&&!a||b.replace(RegExp.$1,"").split("/")[0]===location.host}}(),F=l.matchMedia&&l.matchMedia("only all").matches,y=B.test(l.matchMedia),E=function(){function a(){if(0===e.readyState||4===e.readyState){var a;
(a=g[0])&&c(a);a||b()}}function c(d){k++;e.open("GET",d,!0);e.onreadystatechange=function(){4!=e.readyState||200!=e.status&&304!=e.status||(f[d]=e.responseText,g.shift(),a())};e.send(null)}function b(){for(var a;a=d.shift();){for(var b=a.urls,c=a.fn,k=[],e=0;a=b[e++];)k.push(f[a]);c.call(null,k)}}var f={},g=[],d=[],k=0,e=function(){try{var a=new l.XMLHttpRequest}catch(x){a=new l.ActiveXObject("Microsoft.XMLHTTP")}return a}();return{request:function(c,k){d.push({urls:c,fn:k});for(var e,x=0,r=0;e=c[x++];)f[e]&&
r++;if(r===c.length)b();else{for(x=0;e=c[x++];)f[e]||C(e,g)||g.push(e);a()}},clearCache:function(){f={}},_getRequestCount:function(){return k}}}(),t={_cache:{},clearCache:function(){t._cache={}},parse:function(a,c){function b(){return d(/^\{\s*/)}function f(){return d(/^\}\s*/)}function g(){var c,b=[];d(/^\s*/);for(k(b);"}"!=a.charAt(0)&&(c=l()||m()||n()||u("import")||u("charset")||u("namespace")||p()||q());)b.push(c),k(b);return b}function d(d){if(d=d.exec(a))return a=a.slice(d[0].length),d}function k(a){a=
a||[];for(var d;d=e();)a.push(d);return a}function e(){if("/"==a[0]&&"*"==a[1]){for(var b=2;"*"!=a[b]||"/"!=a[b+1];)++b;b+=2;var c=a.slice(2,b-2);a=a.slice(b);d(/^\s*/);return{comment:c}}}function r(){var a=d(/^([^{]+)/);if(a)return v(a[0]).split(/\s*,\s*/)}function x(){var a=d(/^(\*?[\-\w]+)\s*/);if(a&&(a=a[0],d(/^:\s*/))){var b=d(/^((?:'(?:\\'|.)*?'|"(?:\\"|.)*?"|\([^\)]*?\)|[^};])+)\s*/);if(b)return b=v(b[0]),d(/^[;\s]*/),{property:a,value:b}}}function h(){for(var a,b=[];a=d(/^(from|to|\d+%|\.\d+%|\d+\.\d+%)\s*/);)b.push(a[1]),
d(/^,\s*/);return b.length?{values:b,declarations:A()}:void 0}function l(){var a=d(/^@([\-\w]+)?keyframes */);if(a){var c=a[1];if(a=d(/^([\-\w]+)\s*/))if(a=a[1],b()){k();for(var e,g=[];e=h();)g.push(e),k();if(f())return a={name:a,keyframes:g},c&&(a.vendor=c),a}}}function n(){var a=d(/^@supports *([^{]+)/);if(a&&(a=v(a[1]),b())){k();var c=g();if(f())return{supports:a,rules:c}}}function m(){var a=d(/^@media *([^{]+)/);if(a&&(a=v(a[1]),b())){k();var c=g();if(f())return{media:a,rules:c}}}function p(){if(d(/^@page */)){var a=
r()||[],c=[];if(b()){k();for(var e;e=x()||G();)c.push(e),k();if(f())return{type:"page",selectors:a,declarations:c}}}}function G(){var a=d(/^@([a-z\-]+) */);if(a)return{type:a[1],declarations:A()}}function u(a){var b=d(new RegExp("^@"+a+" *([^;\\n]+);\\s*"));if(b){var c={};return c[a]=v(b[1]),c}}function A(){var a=[];if(b()){k();for(var c;c=x();)a.push(c),k();if(f())return a}}function q(){var a=r();if(a)return k(),{selectors:a,declarations:A()}}return c&&t._cache[c]?t._cache[c]:(a=a.replace(/\/\*[\s\S]*?\*\//g,
""),t._cache[c]=g())},filter:function(a,c){function b(a,b){return a||b?a?a.concat(b):[b]:void 0}function f(a){null==a.media&&delete a.media;null==a.supports&&delete a.supports;d.push(a)}function g(a,d,r){for(var e,k=0;e=a[k++];)if(e.declarations){var h=e,l=d,n=r,p;if(p=c.selectors)a:{p=h.selectors.join(",");var m=c.selectors;if(m)for(var u=m.length;u--;)if(0<=p.indexOf(m[u])){p=!0;break a}p=void 0}if(!p||(f({media:l,supports:n,selectors:h.selectors,declarations:h.declarations}),!1))a:{var q;h=d;l=
r;if(c.declarations)for(n=0;q=e.declarations[n++];){b:{u=m=p=void 0;for(var t=q,w=c.declarations,y=/\*/,z=0;q=w[z++];)if(u=q.split(":"),m=new RegExp("^"+v(u[0]).replace(y,".*")+"$"),p=new RegExp("^"+v(u[1]).replace(y,".*")+"$"),m.test(t.property)&&p.test(t.value)){p=!0;break b}p=void 0}if(p){f({media:h,supports:l,selectors:e.selectors,declarations:e.declarations});break a}}}}else e.rules&&e.media?g(e.rules,b(d,e.media),r):e.rules&&e.supports&&g(e.rules,d,b(r,e.supports))}var d=[];return g(a),d}},
q=function(){function a(){if(c)return c;var a=n.documentElement,b=n.body,e=a.style.fontSize,f=b.style.fontSize,g=n.createElement("div");return a.style.fontSize="1em",b.style.fontSize="1em",b.appendChild(g),g.style.width="1em",g.style.position="absolute",c=g.offsetWidth,b.removeChild(g),b.style.fontSize=f,a.style.fontSize=e,c}var c,b,f=/\(min\-width:[\s]*([\s]*[0-9\.]+)(px|em)[\s]*\)/,g=/\(max\-width:[\s]*([\s]*[0-9\.]+)(px|em)[\s]*\)/;return{matchMedia:function(c){if(F)c=l.matchMedia(c);else{var d,
e,h=!1;c=(b=n.documentElement.clientWidth,f.test(c)&&(d="em"===RegExp.$2?parseFloat(RegExp.$1)*a():parseFloat(RegExp.$1)),g.test(c)&&(e="em"===RegExp.$2?parseFloat(RegExp.$1)*a():parseFloat(RegExp.$1)),d&&e?h=b>=d&&e>=b:(d&&b>=d&&(h=!0),e&&e>=b&&(h=!0)),{matches:h,media:c})}return c},clearCache:function(){y||(b=null)}}}(),z=function(){function a(a,b){var c;return function(){clearTimeout(c);c=setTimeout(a,b)}}var c=function(){var a=[];return{add:function(b,c,f){for(var d,g=0;d=a[g++];)if(d.polyfill==
b&&d.mql===c&&d.fn===f)return!1;c.addListener(f);a.push({polyfill:b,mql:c,fn:f})},remove:function(b){for(var c,f=0;c=a[f++];)c.polyfill===b&&(c.mql.removeListener(c.fn),a.splice(--f,1))}}}(),b=function(a){function c(){for(var c,b=0;c=a[b++];)c.fn()}return{add:function(b,f){a.length||(l.addEventListener?l.addEventListener("resize",c,!1):l.attachEvent("onresize",c));a.push({polyfill:b,fn:f})},remove:function(b){for(var d,e=0;d=a[e++];)d.polyfill===b&&a.splice(--e,1);a.length||(l.removeEventListener?
l.removeEventListener("resize",c,!1):l.detachEvent&&l.detachEvent("onresize",c))}}}([]);return{removeListeners:function(a){y?c.remove(a):b.remove(a)},addListeners:function(f,g){var d=f._mediaQueryMap,h={};!function(){for(var a in d)d.hasOwnProperty(a)&&(h[a]=q.matchMedia(a).matches)}();(function(){if(y)for(var e in d)d.hasOwnProperty(e)&&!function(a,b){c.add(f,a,function(){g.call(f,b,a.matches)})}(d[e],e);else e=a(function(a,c){return function(){var b,d={};q.clearCache();for(b in c)c.hasOwnProperty(b)&&
(d[b]=q.matchMedia(b).matches,d[b]!=h[b]&&g.call(a,b,q.matchMedia(b).matches));h=d}}(f,d),f._options.debounceTimeout||100),b.add(f,e)})()}}}();m.prototype.each=function(a,c){var b,f=0;for(c||(c=this);b=this._rules[f++];)a.call(c,b)};m.prototype.size=function(){return this._rules.length};m.prototype.at=function(a){return this._rules[a]};w.prototype.getDeclaration=function(){for(var a,c={},b=0,f=this._rule.declarations;a=f[b++];)c[a.property]=a.value;return c};w.prototype.getSelectors=function(){return this._rule.selectors.join(", ")};
w.prototype.getMedia=function(){return this._rule.media.join(" and ")};h.prototype.doMatched=function(a){return this._doMatched=a,this._resolve(),this};h.prototype.undoUnmatched=function(a){return this._undoUnmatched=a,this._resolve(),this};h.prototype.getCurrentMatches=function(){for(var a,c,b=0,f=[];a=this._filteredRules[b++];)(c=a.media&&a.media.join(" and "))&&!q.matchMedia(c).matches||f.push(a);return new m(f)};h.prototype.destroy=function(){this._undoUnmatched&&(this._undoUnmatched(this.getCurrentMatches()),
z.removeListeners(this))};h.prototype._defer=function(a,c){a.call(this)?c.call(this):this._promise.push({condition:a,callback:c})};h.prototype._resolve=function(){for(var a,c=0;a=this._promise[c];)a.condition.call(this)?(this._promise.splice(c,1),a.callback.call(this)):c++};h.prototype._getStylesheets=function(){var a,c,b,f,g=0,d=[];if(this._options.include)for(c=this._options.include;a=c[g++];){if(b=n.getElementById(a))"STYLE"===b.nodeName?(a={text:b.textContent},d.push(a)):b.media&&"print"==b.media||
!D(b.href)||(a={href:b.href},b.media&&(a.media=b.media),d.push(a))}else{c=this._options.exclude;for(f=n.getElementsByTagName("link");b=f[g++];)b.rel&&"stylesheet"==b.rel&&"print"!=b.media&&D(b.href)&&!C(b.id,c)&&(a={href:b.href},b.media&&(a.media=b.media),d.push(a));c=n.getElementsByTagName("style");for(g=0;a=c[g++];)a={text:a.textContent},d.push(a)}return this._stylesheets=d};h.prototype._downloadStylesheets=function(){for(var a,c=this,b=[],f=0;a=this._stylesheets[f++];)b.push(a.href);E.request(b,
function(a){for(var b,f=0;b=a[f];)c._stylesheets[f++].text=b;c._resolve()})};h.prototype._parseStylesheets=function(){this._defer(function(){return this._stylesheets&&this._stylesheets.length&&this._stylesheets[0].text},function(){for(var a,c=0;a=this._stylesheets[c++];)a.rules=t.parse(a.text,a.url)})};h.prototype._filterCSSByKeywords=function(){this._defer(function(){return this._stylesheets&&this._stylesheets.length&&this._stylesheets[0].rules},function(){for(var a,c,b=[],f=0;a=this._stylesheets[f++];)(c=
a.media)&&"all"!=c&&"screen"!=c?b.push({rules:a.rules,media:a.media}):b=b.concat(a.rules);this._filteredRules=t.filter(b,this._options.keywords)})};h.prototype._buildMediaQueryMap=function(){this._defer(function(){return this._filteredRules},function(){var a,c,b=0;for(this._mediaQueryMap={};c=this._filteredRules[b++];)c.media&&(a=c.media.join(" and "),this._mediaQueryMap[a]=q.matchMedia(a))})};h.prototype._reportInitialMatches=function(){this._defer(function(){return this._filteredRules&&this._doMatched},
function(){this._doMatched(this.getCurrentMatches())})};h.prototype._addMediaListeners=function(){this._defer(function(){return this._filteredRules&&this._doMatched&&this._undoUnmatched},function(){z.addListeners(this,function(a,c){for(var b,f=0,g=[],d=[];b=this._filteredRules[f++];)b.media&&b.media.join(" and ")==a&&(c?g:d).push(b);g.length&&this._doMatched(new m(g));d.length&&this._undoUnmatched(new m(d))})})};h.modules={DownloadManager:E,StyleManager:t,MediaManager:q,EventManager:z};h.constructors=
{Ruleset:m,Rule:w};l.Polyfill=h}(window,document);